In [7]:
from transition import transition
import numpy as np
ic = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [1, 0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0, 1],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
])
srt = np.array([[
    [
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ]
], [
    [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
]])
print(transition(ic=ic, srt=srt, steps=2))

[[[0 0 0 0 0 0]
  [0 1 1 0 0 0]
  [1 0 0 1 0 0]
  [0 0 1 1 0 1]
  [0 1 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 1 1 1 0 0]
  [0 0 0 0 0 0]
  [0 1 1 0 0 0]
  [0 0 1 1 1 0]
  [0 0 0 0 0 0]]

 [[1 0 1 0 1 0]
  [0 1 0 1 0 1]
  [1 0 1 0 1 0]
  [0 1 0 1 0 1]
  [1 0 1 0 1 0]
  [0 1 0 1 0 1]]]
