In [1]:
from transition import transition
from nsica import NSICAPerceive, NSICAUpdate
from flax import nnx
import numpy as np
def sica1():
    ic = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 1, 1, 0, 0, 0],
    [1, 0, 0, 1, 0, 0],
    [0, 0, 1, 1, 0, 1],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0],
])
    srt = np.array([[
    [
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    ]
], [
    [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
    [
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ],
    [
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
        [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    ],
]])
    print(transition(ic=ic, srt=srt, steps=2, types=2))
    assert(
        np.all(
            transition(ic=ic, srt=srt, steps=2, types=2) == np.array(
                [
                    [
                        [0,0,0,0,0,0],
                        [0,1,1,0,0,0],
                        [1,0,0,1,0,0],
                        [0,0,1,1,0,1],
                        [0,1,0,0,0,0],
                        [0,0,0,0,0,0]
                    ],[
                        [0,0,0,0,0,0],
                        [0,1,1,1,0,0],
                        [0,0,0,0,0,0],
                        [0,1,1,0,0,0],
                        [0,0,1,1,1,0],
                        [0,0,0,0,0,0]
                    ],[
                        [1,0,1,0,1,0],
                        [0,1,0,1,0,1],
                        [1,0,1,0,1,0],
                        [0,1,0,1,0,1],
                        [1,0,1,0,1,0],
                        [0,1,0,1,0,1]
                    ]
                ]
            )
        )
    )


In [ ]:
sica1()

[[[0 0 0 0 0 0]
  [0 1 1 0 0 0]
  [1 0 0 1 0 0]
  [0 0 1 1 0 1]
  [0 1 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 1 1 1 0 0]
  [0 0 0 0 0 0]
  [0 1 1 0 0 0]
  [0 0 1 1 1 0]
  [0 0 0 0 0 0]]

 [[1 0 1 0 1 0]
  [0 1 0 1 0 1]
  [1 0 1 0 1 0]
  [0 1 0 1 0 1]
  [1 0 1 0 1 0]
  [0 1 0 1 0 1]]]


'\n [[7 6 6 7 8 8]\n  [6 6 6 6 7 7]\n  [6 4 3 5 5 6]\n  [5 5 5 6 5 7]\n  [6 7 5 6 6 7]\n  [7 7 7 8 8 8]]\n  '